"""Enforce 1:1 relationship between Conversation and Roadmap

Revision ID: 36b7d591f7e4
Revises: 35cca1248f0a
Create Date: 2026-01-28 17:52:26.379334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36b7d591f7e4'
down_revision: Union[str, Sequence[str], None] = '35cca1248f0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_roadmaps_conversation_id'), 'roadmaps', ['conversation_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_roadmaps_conversation_id'), 'roadmaps', type_='unique')
    # ### end Alembic commands ###
