"""Add uncertainties to blueprint

Revision ID: f3d8acd0bc5c
Revises: 26b82ef8f376
Create Date: 2026-01-31 16:49:31.834205

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f3d8acd0bc5c"
down_revision: Union[str, Sequence[str], None] = "26b82ef8f376"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "blueprints",
        sa.Column(
            "uncertainties",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("blueprints", "uncertainties")
    # ### end Alembic commands ###
